/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "inverse-surface": "#2e3132",
        "surface-tint": "#476083",
        "secondary-container": "#dfe0e0",
        "surface-container-low": "#f3f4f5",
        "error": "#ba1a1a",
        "surface-container-highest": "#e1e3e4",
        "primary-container": "#001f3f",
        "tertiary-fixed": "#d8e2ff",
        "on-background": "#191c1d",
        "secondary-fixed-dim": "#c6c6c7",
        "primary-fixed": "#d4e3ff",
        "on-primary-container": "#6f88ad",
        "on-surface-variant": "#43474e",
        "on-secondary-fixed-variant": "#454747",
        "on-primary-fixed": "#001c3a",
        "primary-fixed-dim": "#afc8f0",
        "background": "#f8f9fa",
        "on-tertiary": "#ffffff",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "inverse-primary": "#afc8f0",
        "on-surface": "#191c1d",
        "tertiary": "#000515",
        "surface-container": "#edeeef",
        "surface": "#f8f9fa",
        "outline-variant": "#c4c6cf",
        "surface-bright": "#f8f9fa",
        "error-container": "#ffdad6",
        "secondary-fixed": "#e2e2e2",
        "surface-dim": "#d9dadb",
        "on-secondary-container": "#616363",
        "inverse-on-surface": "#f0f1f2",
        "on-tertiary-container": "#2b83ff",
        "on-primary": "#ffffff",
        "on-error-container": "#93000a",
        "on-tertiary-fixed-variant": "#004493",
        "surface-container-high": "#e7e8e9",
        "on-primary-fixed-variant": "#2f486a",
        "secondary": "#5d5f5f",
        "tertiary-fixed-dim": "#adc7ff",
        "primary": "#000613",
        "on-secondary-fixed": "#1a1c1c",
        "on-tertiary-fixed": "#001a41",
        "outline": "#74777f",
        "tertiary-container": "#001d46",
        "surface-variant": "#e1e3e4"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "container-padding": "32px",
        "stack-lg": "48px",
        "base": "8px",
        "stack-md": "24px",
        "stack-sm": "12px",
        "margin-mobile": "16px",
        "gutter": "24px"
      },
      fontFamily: {
        sans: ["Inter", "sans-serif"],
        "headline-lg": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "title-md": ["Inter"],
        "display-lg": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        "label-caps": ["Inter"]
      },
      fontSize: {
        "headline-lg-mobile": ["24px", { "lineHeight": "32px", "fontWeight": "600" }],
        "title-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-caps": ["12px", { "lineHeight": "16px", "letterSpacing": "0.05em", "fontWeight": "700" }],
        "display-lg": ["48px", { "lineHeight": "56px", "letterSpacing": "-0.02em", "fontWeight": "700" }],
        "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "20px", "fontWeight": "400" }],
        "body-lg": ["16px", { "lineHeight": "24px", "fontWeight": "400" }]
      }
    },
  },
  plugins: [],
}
